apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ PROJECT }}-{{ APP_ENV }}-mailer-realtime
  labels:
    cron-job: {{ PROJECT }}-{{ APP_ENV }}-mailer-realtime
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: k8s-cronjob
              image: us-central1-docker.pkg.dev/{{ GCP_PROJECT_ID }}/{{ PROJECT }}/k8s-cronjob:current
              env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ PROJECT }}-{{ APP_ENV }}-sf-secrets
                      key: API_KEY
                - name: URL
                  value: {{ WEB_POD_URL_INTERNAL }}/api/email_send_realtime/$(API_KEY)
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "512Mi"
                  cpu: "250m"
---
# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: {{ PROJECT }}-{{ APP_ENV }}-mailer-batch
#   labels:
#     cron-job: {{ PROJECT }}-{{ APP_ENV }}-mailer-batch
# spec:
#   schedule: "*/10 * * * *"
#   successfulJobsHistoryLimit: 0
#   failedJobsHistoryLimit: 0
#   concurrencyPolicy: Forbid
#   startingDeadlineSeconds: 60
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           restartPolicy: OnFailure
#           containers:
#             - name: k8s-cronjob
#               image: us-central1-docker.pkg.dev/{{ GCP_PROJECT_ID }}/{{ PROJECT }}/k8s-cronjob:current
#               env:
#                 - name: API_KEY
#                   valueFrom:
#                     secretKeyRef:
#                       name: {{ PROJECT }}-{{ APP_ENV }}-sf-secrets
#                       key: API_KEY
#                 - name: URL
#                   value: {{ WEB_POD_URL_INTERNAL }}/api/email_send_batch/$(API_KEY)
#               resources:
#                 requests:
#                   memory: "512Mi"
#                   cpu: "250m"
#                 limits:
#                   memory: "512Mi"
#                   cpu: "250m"
