apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ PROJECT }}-{{ APP_ENV }}
  labels:
    app: {{ PROJECT }}-{{ APP_ENV }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ PROJECT }}-{{ APP_ENV }}

  template:
    metadata:
      labels:
        app: {{ PROJECT }}-{{ APP_ENV }}
        APP_ENV: {{ APP_ENV }}
        tag: {{ TAG }}
    spec:

      containers:
        - name: {{ PROJECT }}-{{ APP_ENV }}-web
          image: {{ PROJECT }}-{{ APP_ENV }}-web:{{ TAG }}
          env:
            - name: SYMFONY_DECRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ PROJECT }}-{{ APP_ENV }}-sf-secrets
                  key: SYMFONY_DECRYPTION_SECRET
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ PROJECT }}-{{ APP_ENV }}-sf-secrets
                  key: API_KEY
            - name: MAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ PROJECT }}-{{ APP_ENV }}-sf-secrets
                  key: MAILER_PASSWORD
          ports:
            - name: {{ PROJECT }}-{{ APP_ENV }}
              containerPort: 80
          volumeMounts:
            - name: {{ PROJECT }}-{{ APP_ENV }}-log
              mountPath: /var/www/log
            # Only for local development
            - name: {{ PROJECT }}-{{ APP_ENV }}-local-storage
              mountPath: /var/www/local-storage
            - name: {{ PROJECT }}-{{ APP_ENV }}-sf
              mountPath: /var/www/sf

      volumes:
        - name: {{ PROJECT }}-{{ APP_ENV }}-log
          emptyDir: {}
        - name: {{ PROJECT }}-{{ APP_ENV }}-local-storage
          hostPath:
            path: {{ HOST_DATA_LOCAL_STORAGE }}
            type: Directory
        - name: {{ PROJECT }}-{{ APP_ENV }}-sf
          hostPath:
            path: {{ HOST_SF_DIR }}
            type: Directory
