apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ PROJECT }}-{{ APP_ENV }}
  labels:
    app: {{ PROJECT }}-{{ APP_ENV }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ PROJECT }}-{{ APP_ENV }}

  template:
    metadata:
      labels:
        app: {{ PROJECT }}-{{ APP_ENV }}
        APP_ENV: {{ APP_ENV }}
        tag: "{{ TAG }}"
    spec:

      initContainers:
        - name: {{ PROJECT }}-{{ APP_ENV }}-webinit
          image: gcr.io/{{ GCP_PROJECT_ID }}/{{ PROJECT }}-{{ APP_ENV }}-webinit:{{ TAG }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              cp -r /var/www/sf/* /sf \
              && cp -r /var/www/sf/.env /sf/.env \
              && cp -r /var/www/cache/* /cache \
              && chown -R 1000:33 /cache \
              && chown -R 1000:33 /sf
#              && chmod 0777 /sf/templates/email/campaign \
          volumeMounts:
            - name: sf
              mountPath: /sf
            - name: cache
              mountPath: /cache

      containers:
        - name: {{ PROJECT }}-{{ APP_ENV }}-web
          image: gcr.io/{{ GCP_PROJECT_ID }}/{{ PROJECT }}-{{ APP_ENV }}-web:{{ TAG }}
          env:
            - name: SYMFONY_DECRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ PROJECT }}-{{ APP_ENV }}-sf-secrets
                  key: SYMFONY_DECRYPTION_SECRET
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ PROJECT }}-{{ APP_ENV }}-sf-secrets
                  key: API_KEY
            - name: MAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ PROJECT }}-{{ APP_ENV }}-sf-secrets
                  key: MAILER_PASSWORD
          ports:
            - name: {{ PROJECT }}-{{ APP_ENV }}
              containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: sf
              mountPath: /var/www/sf
            - name: cache
              mountPath: /var/www/cache

      volumes:
        - name: sf
          emptyDir: {}
        - name: cache
          emptyDir: {}
