apiVersion: v1
kind: Service
metadata:
  name: {{ PROJECT }}-{{ APP_ENV }}
  labels:
    app: {{ PROJECT }}-{{ APP_ENV }}
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: {{ PROJECT }}-{{ APP_ENV }}
