apiVersion: v1
kind: Service
metadata:
  name: {{ BRANCH }}-{{ PROJECT }}
  labels:
    app: {{ BRANCH }}-{{ PROJECT }}
spec:
  type: NodePort
  ports:
    - port: {{ APACHE_LISTEN_PORT }}
      targetPort: {{ APACHE_LISTEN_PORT }}
  selector:
    app: {{ BRANCH }}-{{ PROJECT }}
