flysystem:
    storages:
        storage.private.local:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/../local-storage/%env(GCS_PRIVATE_BUCKET)%'
        storage.public.local:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/../local-storage/%env(GCS_PUBLIC_BUCKET)%'
        storage.private.gcloud:
            adapter: 'gcloud'
            options:
                client: 'Google\Cloud\Storage\StorageClient' # The service ID of the Google\Cloud\Storage\StorageClient instance
                bucket: '%env(GCS_PRIVATE_BUCKET)%'
                prefix: ''
                api_url: 'https://storage.googleapis.com'
        storage.public.gcloud:
            adapter: 'gcloud'
            options:
                client: 'Google\Cloud\Storage\StorageClient' # The service ID of the Google\Cloud\Storage\StorageClient instance
                bucket: '%env(GCS_PUBLIC_BUCKET)%'
                prefix: ''
                api_url: 'https://storage.googleapis.com'
        # Aliases based on environment variable
        storage.private:
            adapter: 'lazy'
            options:
                source: 'storage.private.%env(STORAGE_ADAPTER)%'
        storage.public:
            adapter: 'lazy'
            options:
                source: 'storage.public.%env(STORAGE_ADAPTER)%'
