FROM php:7.3-apache
LABEL maintainer="Eric Jacolin <eric.jacolin@free.fr>"

# Install PHP modules
RUN apt-get update \
    # generic libraries
    && apt-get install -y \
        libssl-dev \
        libxml2-dev \
        curl \
    # PHP modules
    && docker-php-ext-install \
        pdo_mysql \
    # Composer
    && curl -sS https://getcomposer.org/installer \
        | php -- --install-dir=/usr/bin/ --filename=composer \
    # Purge apt
    && apt-get clean -y && apt-get autoclean -y && apt-get autoremove -y \
        && rm -rf /var/lib/apt/lists/*

RUN ln -snf /usr/share/zoneinfo/NZ /etc/localtime

# Dockerize
RUN curl -sfL https://github.com/powerman/dockerize/releases/download/v0.10.0/dockerize-`uname -s`-`uname -m` \
    | install /dev/stdin /usr/local/bin/dockerize

# PHP CLI configuration
COPY infra/php.ini.tpl /usr/local/etc/php/php.ini.tpl

# Install Apache modules
ENV APACHE_RUN_USER  www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR   /var/log/apache2
ENV APACHE_PID_FILE  /var/run/apache2/apache2.pid
ENV APACHE_RUN_DIR   /var/run/apache2
ENV APACHE_LOCK_DIR  /var/lock/apache2
ENV APACHE_LOG_DIR   /var/log/apache2
RUN a2enmod rewrite \
    && a2enmod ssl \
    && a2dissite 000-default.conf \
    && chown -R www-data:www-data /var/www \
    && mkdir -p $APACHE_RUN_DIR \
    && mkdir -p $APACHE_LOCK_DIR \
    && mkdir -p $APACHE_LOG_DIR

# Apache configuration (project-dependent)
COPY infra/php.ini.tpl /etc/php/7.3/apache2/php.ini.tpl
COPY infra/virtual-host.conf.tpl /etc/apache2/sites-enabled/virtual-host.conf.tpl
COPY infra/ports.conf.tpl /etc/apache2/ports.conf.tpl

# Sendmail installation
RUN apt-get update \
&& apt-get install -y \
msmtp msmtp-mta \
# Purge apt
&& apt-get clean -y && apt-get autoclean -y && apt-get autoremove -y \
&& rm -rf /var/lib/apt/lists/*

# MSMTP configuration (project-dependent)
COPY infra/msmtprc.tpl /etc/msmtprc.tpl
COPY infra/msmtp.logrotate /etc/logrotate.d/msmtp

# Web application files
ADD sf.tar.gz /var/www/

# Arguments to build configuration files with dockerize
ARG ROUTER_REQUEST_CONTEXT_HOST
ENV ROUTER_REQUEST_CONTEXT_HOST $ROUTER_REQUEST_CONTEXT_HOST
ARG APACHE_LISTEN_PORT
ENV APACHE_LISTEN_PORT $APACHE_LISTEN_PORT
ARG PHP_DISPLAY_ERRORS
ENV PHP_DISPLAY_ERRORS $PHP_DISPLAY_ERRORS
ARG PHP_ERROR_REPORTING
ENV PHP_ERROR_REPORTING $PHP_ERROR_REPORTING

# To allow SF to write to var/cache and log on mounted volumes
RUN usermod -u 1000 www-data

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--", "docker-php-entrypoint"]

#CMD ["apachectl", "-D", "FOREGROUND"]
CMD ["dockerize", \
    "-template", "/usr/local/etc/php/php.ini.tpl:/usr/local/etc/php/php.ini", \
    "-template", "/etc/php/7.3/apache2/php.ini.tpl:/etc/php/7.3/apache2/php.ini", \
    "-template", "/etc/apache2/sites-enabled/virtual-host.conf.tpl:/etc/apache2/sites-enabled/virtual-host.conf", \
    "-template", "/etc/apache2/ports.conf.tpl:/etc/apache2/ports.conf", \
    "-template", "/etc/msmtprc.tpl:/etc/msmtprc", \
    "apachectl", "-D", "FOREGROUND"]
