monolog:
    handlers:
        main:
            type:       fingers_crossed
            action_level: error
            handler:    grouped
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        grouped:
            type:       group
            members:    [streamed, deduplicated]
        streamed:
            type:       rotating_file
            path:       "%kernel.logs_dir%/%kernel.environment%.log"
            level:      debug
            max_files:  10
        deduplicated:
            type:       deduplication
            handler:    symfony_mailer
        symfony_mailer:
            type:       symfony_mailer
            from_email: "%email_from%"
            to_email:   "%email_from%"
            subject:    'An Error Occurred! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
